require('dotenv').config();
const mongoose = require('mongoose');
const Book = require('../models/Book');
const Category = require('../models/Category');

const seedMalayalamStore = async () => {
  try {
    console.log('[LOGOS Seed] Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('[LOGOS Seed] MongoDB Connected.');

    const books = [
      {
        title: 'Mani Muzhangunnathu Aarkku Vendi',
        name: 'മണിമുഴങ്ങുന്നത് ആർക്കുവേണ്ടി',
        slug: 'manimuzhangunnathu-aarkkuvendi',
        author: 'Ernest Hemingway',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Novel',
        genre: 'Historical Fiction, War Literature',
        languages: ['Malayalam'],
        pageCount: 146,
        description: "Mani Muzhangunnathu Aarkkuvendi is the Malayalam translation of Ernest Hemingway's celebrated novel For Whom the Bell Tolls. Set against the backdrop of the Spanish Civil War, the novel follows Robert Jordan, an American volunteer fighting alongside the Republican forces. The story brings together themes of love, war, sacrifice, courage, death, and human relationships. Hemingway presents the emotional and psychological experiences of people caught in the middle of conflict.",
        price: 860,
        discountPrice: 616,
        stock: 50,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-001',
        isbn: '9789347536090',
        images: [
          '/product_detail_main.png',
          '/product_thumb1.png',
          '/product_thumb2.png',
          '/handpicked2.png'
        ],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: true,
        rating: 5.4,
        reviewsCount: 146,
        isActive: true
      },
      {
        title: 'അപരാഹ്നത്തിലെ മരണം',
        name: 'അപരാഹ്നത്തിലെ മരണം',
        slug: 'aparahnatthile-maranam',
        author: 'വിവർത്തനം സുരേഷ് , എം . ജി',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Novel',
        genre: 'Literature',
        languages: ['Malayalam'],
        pageCount: 220,
        description: 'ഏണസ്റ്റ് ഹെമിംഗ്‌വേയുടെ പ്രസിദ്ധമായ നോവലിന്റെ മലയാള പരിഭാഷ.',
        price: 499,
        discountPrice: 354,
        stock: 40,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-002',
        isbn: '9789347536091',
        images: ['/book1.jpg'],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 88,
        isActive: true
      },
      {
        title: 'ഫോർ ജസ്റ്റിസ്',
        name: 'ഫോർ ജസ്റ്റിസ്',
        slug: 'four-justice',
        author: 'അജീഷ് ഗംഗാധരൻ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Thriller',
        genre: 'Fiction',
        languages: ['Malayalam'],
        pageCount: 190,
        description: 'നീതിക്കായുള്ള പോരാട്ടത്തിന്റെ തീവ്രമായ കഥ പറയുന്ന നോവൽ.',
        price: 495,
        discountPrice: 338,
        stock: 35,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-003',
        isbn: '9789347536092',
        images: ['/book2.png'],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 64,
        isActive: true
      },
      {
        title: 'ഡാർക്ക് ഫാന്റസി',
        name: 'ഡാർക്ക് ഫാന്റസി',
        slug: 'dark-fantasy',
        author: 'ജിസ ജോൺ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Fantasy',
        genre: 'Sci-Fi & Fantasy',
        languages: ['Malayalam'],
        pageCount: 160,
        description: 'നിഗൂഢതകളും മാന്ത്രികതയും നിറഞ്ഞ ഒരു ലോകത്തിന്റെ രഹസ്യങ്ങൾ.',
        price: 200,
        discountPrice: 170,
        stock: 45,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-004',
        isbn: '9789347536093',
        images: ['/book3.png'],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 52,
        isActive: true
      },
      {
        title: 'മുക്തകണ്ഠം വികെഎൻ (HARD BOUND)',
        name: 'മുക്തകണ്ഠം വികെഎൻ',
        slug: 'mukthakandam-vkn',
        author: 'കെ. രഘുനാഥൻ',
        publisher: 'LOGOS BOOKS',
        edition: 'Hard Bound Deluxe',
        theme: 'Biography',
        genre: 'Memoirs & Essays',
        languages: ['Malayalam'],
        pageCount: 310,
        description: 'വികെഎൻ സാഹിത്യത്തെയും ജീവിതത്തെയും കുറിച്ചുള്ള ആഴത്തിലുള്ള പഠനം.',
        price: 650,
        discountPrice: 432,
        stock: 25,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-005',
        isbn: '9789347536094',
        images: ['/book4.png'],
        isBestSeller: false,
        isNewArrival: true,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 110,
        isActive: true
      },
      {
        title: 'കമ്മ്യൂണിസ്റ്റ് ഹീറോ',
        name: 'കമ്മ്യൂണിസ്റ്റ് ഹീറോ',
        slug: 'communist-hero',
        author: 'പി.ടി. പ്രദീഷ്',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Politics & History',
        genre: 'Biography',
        languages: ['Malayalam'],
        pageCount: 180,
        description: 'വി എസ് അച്യുതാനന്ദന്റെ വിപ്ലവകരമായ രാഷ്ട്രീയ ജീവിതത്തിന്റെ ഏടുകൾ.',
        price: 160,
        discountPrice: 94,
        stock: 60,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-006',
        isbn: '9789347536095',
        images: ['/bestseller1.png'],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 220,
        isActive: true
      },
      {
        title: 'കുമ്പളമ്പറമ്പിലെ കുമ്പുളുമൂസുകൾ',
        name: 'കുമ്പളമ്പറമ്പിലെ കുമ്പുളുമൂസുകൾ',
        slug: 'kumbalamparambile-kumbulumusukal',
        author: 'ദാമോദർ രാധാകൃഷ്ണൻ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Stories',
        genre: 'Children & Family',
        languages: ['Malayalam'],
        pageCount: 120,
        description: 'ഗ്രാമീണ ജീവിതത്തിന്റെ നന്മയും തമാശകളും നിറഞ്ഞ കഥകൾ.',
        price: 110,
        discountPrice: 64,
        stock: 50,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-007',
        isbn: '9789347536096',
        images: ['/bestseller2.png'],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 95,
        isActive: true
      },
      {
        title: 'മിലുപ്പ എന്ന കുതിര',
        name: 'മിലുപ്പ എന്ന കുതിര',
        slug: 'miluppa-enna-kuthira',
        author: 'സന്തോഷ് ഏച്ചിക്കാനം',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Literature',
        genre: 'Short Stories',
        languages: ['Malayalam'],
        pageCount: 140,
        description: 'സന്തോഷ് ഏച്ചിക്കാനത്തിന്റെ വേറിട്ട ഭാവുകത്വമുള്ള കഥാസമാഹാരം.',
        price: 180,
        discountPrice: 112,
        stock: 45,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-008',
        isbn: '9789347536097',
        images: ['/bestseller3.png'],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 130,
        isActive: true
      },
      {
        title: 'രണ്ടുപക്ഷം',
        name: 'രണ്ടുപക്ഷം',
        slug: 'randupaksham',
        author: 'യു .കെ .കുമാരൻ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Novel',
        genre: 'Fiction',
        languages: ['Malayalam'],
        pageCount: 165,
        description: 'മനുഷ്യ മനസ്സിന്റെ സങ്കീർണ്ണതകളിലൂടെയുള്ള തീക്ഷ്ണമായ സഞ്ചാരം.',
        price: 140,
        discountPrice: 80,
        stock: 40,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-009',
        isbn: '9789347536098',
        images: ['/bestseller4.png'],
        isBestSeller: true,
        isNewArrival: false,
        isFeatured: false,
        rating: 5.4,
        reviewsCount: 115,
        isActive: true
      },
      {
        title: 'ദൈവമെന്ന മനുഷ്യൻ',
        name: 'ദൈവമെന്ന മനുഷ്യൻ',
        slug: 'daivamanna-manushyan',
        author: 'വിനീഷ് കെ.എൻ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Novel',
        genre: 'Philosophy & Fiction',
        languages: ['Malayalam'],
        pageCount: 155,
        description: 'മനുഷ്യത്വത്തിന്റെയും അതിജീവനത്തിന്റെയും കഥ.',
        price: 180,
        discountPrice: 104,
        stock: 55,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-010',
        isbn: '9789347536099',
        images: ['/handpicked1.png'],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        rating: 5.4,
        reviewsCount: 78,
        isActive: true
      },
      {
        title: 'കണക്കിലെ ചിരികൾ',
        name: 'കണക്കിലെ ചിരികൾ',
        slug: 'kanakkile-chirikal',
        author: 'അമിത് കുമാർ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Humour',
        genre: 'Essays & Humour',
        languages: ['Malayalam'],
        pageCount: 175,
        description: 'ഒരു ബാങ്കുദ്യോഗസ്ഥന്റെ അനുഭവക്കുറിപ്പുകൾ നിറഞ്ഞ രസകരമായ പുസ്തകം.',
        price: 270,
        discountPrice: 178,
        stock: 35,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-011',
        isbn: '9789347536100',
        images: ['/handpicked3.png'],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        rating: 5.4,
        reviewsCount: 92,
        isActive: true
      },
      {
        title: 'പരാജിതനായകർ',
        name: 'പരാജിതനായകർ',
        slug: 'parajithanayakar',
        author: 'ടി. അനീഷ്',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Cinema & Politics',
        genre: 'Non-Fiction',
        languages: ['Malayalam'],
        pageCount: 240,
        description: 'തമിഴ് സിനിമയും രാഷ്ട്രീയവും തമ്മിലുള്ള ആഴത്തിലുള്ള ബന്ധം വ്യക്തമാക്കുന്നതാണ് ഈ പുസ്തകം. എം.ജി.ആർ, ജയലളിത തുടങ്ങിയവർ തമിഴ് രാഷ്ട്രീയത്തിൽ വലിയ വിജയങ്ങൾ കൊയ്തപ്പോൾ, രാഷ്ട്രീയത്തിൽ പരാജയപ്പെടുകയോ അല്ലെങ്കിൽ വലിയ ചലനങ്ങൾ സൃഷ്ടിക്കാൻ കഴിയാതെ പോവുകയോ ചെയ്ത ശിവാജി ഗണേശൻ, വിജയകാന്ത്, കമൽ ഹാസൻ, രജനീകാന്ത് തുടങ്ങിയ താരങ്ങളുടെ രാഷ്ട്രീയ ശ്രമങ്ങളെയും അവരുടെ സിനിമകളെയും ഈ പുസ്തകം വിലയിരുത്തുന്നു.',
        price: 380,
        discountPrice: 380,
        stock: 50,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-012',
        isbn: '9789347536101',
        images: ['/featured_parajitha.png'],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        rating: 5.4,
        reviewsCount: 140,
        isActive: true
      },
      {
        title: 'ഘടോൽക്കചൻ',
        name: 'ഘടോൽക്കചൻ',
        slug: 'ghadolkachan',
        author: 'രാജേഷ് കെ.ആർ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Novel',
        genre: 'Mythology & Literature',
        languages: ['Malayalam'],
        pageCount: 210,
        description: 'പാണ്ഡവർക്കായി ധീരമായി പോരാടിയ ഘടോൽക്കചൻ കർണ്ണന്റെ ആയുധത്താൽ വീരമൃത്യു വരിക്കുന്നു.',
        price: 350,
        discountPrice: 290,
        stock: 30,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-013',
        isbn: '9789347536102',
        images: ['/author_best1.png'],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        rating: 5.4,
        reviewsCount: 65,
        isActive: true
      },
      {
        title: 'ഘടോൽക്കചൻ - രാക്ഷസപർവ്വം',
        name: 'ഘടോൽക്കചൻ - രാക്ഷസപർവ്വം',
        slug: 'ghadolkachan-rakshasaparvam',
        author: 'രാജേഷ് കെ.ആർ',
        publisher: 'LOGOS BOOKS',
        edition: '1',
        theme: 'Novel',
        genre: 'Mythology & Literature',
        languages: ['Malayalam'],
        pageCount: 230,
        description: 'ഘടോൽക്കചൻ പാണ്ഡവർക്കായി പോരാടിയ ധീരനായ യോദ്ധാവായിരുന്നു.',
        price: 380,
        discountPrice: 320,
        stock: 25,
        stockStatus: 'in_stock',
        sku: 'LGS-MAL-014',
        isbn: '9789347536103',
        images: ['/author_best2.png'],
        isBestSeller: false,
        isNewArrival: false,
        isFeatured: true,
        rating: 5.4,
        reviewsCount: 72,
        isActive: true
      }
    ];

    for (const b of books) {
      await Book.findOneAndUpdate({ slug: b.slug }, b, { upsert: true, new: true });
      console.log(`[LOGOS Seed] Upserted book: ${b.title}`);
    }

    console.log('[LOGOS Seed] Completed successfully!');
    process.exit(0);
  } catch (err) {
    console.error('[LOGOS Seed] Error:', err);
    process.exit(1);
  }
};

seedMalayalamStore();
